channels:
- conda-forge
dependencies:
- python=3.10.6
- pip<=23.1.2
- pip:
  - mlflow==2.8.1
  - cloudpickle==2.2.0
  - numpy==1.22.2
  - packaging==21.3
  - pandas==1.4.1
  - psutil==5.9.1
  - pyyaml==6.0
  - scikit-learn==1.2.2
  - scipy==1.10.0
  - xgboost==2.0.2
name: mlflow-env
